# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from app.grpc import car_booking_pb2 as car__booking__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in car_booking_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookCar = channel.unary_unary(
            "/booking.BookingService/BookCar",
            request_serializer=car__booking__pb2.BookCarRequest.SerializeToString,
            response_deserializer=car__booking__pb2.BookCarResponse.FromString,
            _registered_method=True,
        )
        self.RestoreAvailability = channel.unary_unary(
            "/booking.BookingService/RestoreAvailability",
            request_serializer=car__booking__pb2.RestoreAvailabilityRequest.SerializeToString,
            response_deserializer=car__booking__pb2.RestoreAvailabilityResponse.FromString,
            _registered_method=True,
        )


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RestoreAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "BookCar": grpc.unary_unary_rpc_method_handler(
            servicer.BookCar,
            request_deserializer=car__booking__pb2.BookCarRequest.FromString,
            response_serializer=car__booking__pb2.BookCarResponse.SerializeToString,
        ),
        "RestoreAvailability": grpc.unary_unary_rpc_method_handler(
            servicer.RestoreAvailability,
            request_deserializer=car__booking__pb2.RestoreAvailabilityRequest.FromString,
            response_serializer=car__booking__pb2.RestoreAvailabilityResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "booking.BookingService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("booking.BookingService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookCar(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/booking.BookingService/BookCar",
            car__booking__pb2.BookCarRequest.SerializeToString,
            car__booking__pb2.BookCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RestoreAvailability(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/booking.BookingService/RestoreAvailability",
            car__booking__pb2.RestoreAvailabilityRequest.SerializeToString,
            car__booking__pb2.RestoreAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
