# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking_payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'booking_payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62ooking_payment.proto\x12\x07\x62ooking\"1\n\x1bGetBookingForPaymentRequest\x12\x12\n\nbooking_id\x18\x01 \x01(\x05\"\x8a\x01\n\x1cGetBookingForPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nbooking_id\x18\x03 \x01(\x05\x12\x13\n\x0btotal_price\x18\x04 \x01(\x02\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0f\n\x07\x63\x61n_pay\x18\x06 \x01(\x08\"K\n!UpdateBookingPaymentStatusRequest\x12\x12\n\nbooking_id\x18\x01 \x01(\x05\x12\x12\n\nnew_status\x18\x02 \x01(\t\"F\n\"UpdateBookingPaymentStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf3\x01\n\x15\x42ookingPaymentService\x12\x63\n\x14GetBookingForPayment\x12$.booking.GetBookingForPaymentRequest\x1a%.booking.GetBookingForPaymentResponse\x12u\n\x1aUpdateBookingPaymentStatus\x12*.booking.UpdateBookingPaymentStatusRequest\x1a+.booking.UpdateBookingPaymentStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKINGFORPAYMENTREQUEST']._serialized_start=34
  _globals['_GETBOOKINGFORPAYMENTREQUEST']._serialized_end=83
  _globals['_GETBOOKINGFORPAYMENTRESPONSE']._serialized_start=86
  _globals['_GETBOOKINGFORPAYMENTRESPONSE']._serialized_end=224
  _globals['_UPDATEBOOKINGPAYMENTSTATUSREQUEST']._serialized_start=226
  _globals['_UPDATEBOOKINGPAYMENTSTATUSREQUEST']._serialized_end=301
  _globals['_UPDATEBOOKINGPAYMENTSTATUSRESPONSE']._serialized_start=303
  _globals['_UPDATEBOOKINGPAYMENTSTATUSRESPONSE']._serialized_end=373
  _globals['_BOOKINGPAYMENTSERVICE']._serialized_start=376
  _globals['_BOOKINGPAYMENTSERVICE']._serialized_end=619
# @@protoc_insertion_point(module_scope)
