# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from app.grpc import booking_payment_pb2 as booking__payment__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in booking_payment_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BookingPaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookingForPayment = channel.unary_unary(
            "/booking.BookingPaymentService/GetBookingForPayment",
            request_serializer=booking__payment__pb2.GetBookingForPaymentRequest.SerializeToString,
            response_deserializer=booking__payment__pb2.GetBookingForPaymentResponse.FromString,
            _registered_method=True,
        )
        self.UpdateBookingPaymentStatus = channel.unary_unary(
            "/booking.BookingPaymentService/UpdateBookingPaymentStatus",
            request_serializer=booking__payment__pb2.UpdateBookingPaymentStatusRequest.SerializeToString,
            response_deserializer=booking__payment__pb2.UpdateBookingPaymentStatusResponse.FromString,
            _registered_method=True,
        )


class BookingPaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookingForPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateBookingPaymentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BookingPaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetBookingForPayment": grpc.unary_unary_rpc_method_handler(
            servicer.GetBookingForPayment,
            request_deserializer=booking__payment__pb2.GetBookingForPaymentRequest.FromString,
            response_serializer=booking__payment__pb2.GetBookingForPaymentResponse.SerializeToString,
        ),
        "UpdateBookingPaymentStatus": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateBookingPaymentStatus,
            request_deserializer=booking__payment__pb2.UpdateBookingPaymentStatusRequest.FromString,
            response_serializer=booking__payment__pb2.UpdateBookingPaymentStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "booking.BookingPaymentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "booking.BookingPaymentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class BookingPaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookingForPayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/booking.BookingPaymentService/GetBookingForPayment",
            booking__payment__pb2.GetBookingForPaymentRequest.SerializeToString,
            booking__payment__pb2.GetBookingForPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateBookingPaymentStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/booking.BookingPaymentService/UpdateBookingPaymentStatus",
            booking__payment__pb2.UpdateBookingPaymentStatusRequest.SerializeToString,
            booking__payment__pb2.UpdateBookingPaymentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
