global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user_service"
    static_configs:
      - targets: ["user_service:8000"]

  - job_name: "car_service"
    static_configs:
      - targets: ["car_service:8001"]

  - job_name: "booking_service"
    static_configs:
      - targets: ["booking_service:8002"]
